### ISSUE TITLE
CFP link does not work on mobile

### ISSUE THREAD

**Issue by asgrim** [phphants/php-south-coast-2017#13]
The link is not visible on some ojoens???

**Comment by lboynton** [comment]
Ojoens? Have you got a screenshot?

**Comment by asgrim** [comment]
"Phones" haha. No sorry, no screenshot, it was on an android device, but it worked on mine but not Rowan's :s couldn't tell what the issue was from just looking at it tho

**Comment by lboynton** [comment]
Works OK on my phone too. Will be difficult to fix without being able to reproduce...

**Comment by lboynton** [comment]
I guess we can close this issue now that CFP is closed!
